Description of smooth_batch
smooth_batch
PURPOSE
-----------------------------------------------------------------------
SYNOPSIS
This is a script file.
DESCRIPTION
-----------------------------------------------------------------------
 Job configuration created by cfg_util (rev $Rev: 4252 $)
-----------------------------------------------------------------------
%
CROSS-REFERENCE INFORMATION
This function calls:
get_scans_concatenated
This function is called by:
preprocessing
preprocessing
SOURCE CODE
%-----------------------------------------------------------------------
% Job configuration created by cfg_util (rev $Rev: 4252 $)
%-----------------------------------------------------------------------
%%
matlabbatch{1}.spm.spatial.smooth.data = get_scans_concatenated(preproc_dir, nrun, nvol, ['war' run_file_prefix], run_file_suffix);
matlabbatch{1}.spm.spatial.smooth.fwhm = smooth;
matlabbatch{1}.spm.spatial.smooth.dtype = 0;
matlabbatch{1}.spm.spatial.smooth.im = 0;
matlabbatch{1}.spm.spatial.smooth.prefix = 's';