Description of Generic
Generic
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
Generic
This function is called by:
Mascara
Var
Classifier
GA
Individuo
Report
Generic
SUBFUNCTIONS
function params = toStruct(obj)
SOURCE CODE
classdef Generic < handle
    %GENERIC Summary of this class goes here
    %   Detailed explanation goes here
    properties
    end
    methods
        function params = toStruct(obj)
            props = properties(obj);
            for k=1:length(props)
                params.(props{k}) = obj.(props{k});
            end
        end
    end
end