Description of qstat
qstat
PURPOSE
QSTAT Summary of this function goes here
SYNOPSIS
function out = qstat(varargin)
DESCRIPTION
QSTAT Summary of this function goes here
   Detailed explanation goes here
CROSS-REFERENCE INFORMATION
This function calls:
qstat QSTAT Summary of this function goes here
qstat QSTAT Summary of this function goes here
This function is called by:
jobInfo EXTRACTJOBINFO Summary of this function goes here
qstat QSTAT Summary of this function goes here
SOURCE CODE
function out = qstat(varargin)
%QSTAT Summary of this function goes here
%   Detailed explanation goes here
import idor.blade.*
output = qstat(varargin{:});
if(nargout > 0)
    out = output;
else
    disp(output);
end
end