Description of exec_procs
exec_procs
PURPOSE
Abre SPM para gerar gr치ficos
SYNOPSIS
function exec_procs(config)
DESCRIPTION
 Abre SPM para gerar gr치ficos
CROSS-REFERENCE INFORMATION
This function calls:
extract_betas
preprocessing
run_first_level
run_second_level
preprocessing
run_first_level
run_second_level
This function is called by:
SOURCE CODE
function exec_procs(config)
% Abre SPM para gerar gr치ficos
if isempty(spm('Figname'))
    spm fmri;
end
if config.do.preprocessing
    preprocessing( config );
end
%% FIRST LEVEL
if config.do.first_level
    run_first_level( config );
end
if config.do.second_level
    run_second_level( config );
end
if config.do.extract_betas
    extract_betas( config );
end