areas = [8:16 24 25 32 33 46];
mask = Mascara(brodmann);
mask.addAreas(areas);
ga = GA({}, areas);
ga.classifier.preProc = true;
ga.classifier.baseline = -9:-8;
ga.classifier.activation = -7:-6;
%individuo = Individuo(mask, {'SUBJ010','SUBJ011'});
individuo = Individuo(mask, {'SUBJ011'});
ga.classifier.classificar(individuo);