Description of find
find
PURPOSE
Find file using regular expression
SYNOPSIS
function [ output ] = find(dirdata, pattern, type, depth)
DESCRIPTION
Find file using regular expression
   Example of use: find( '/dados1', '.*(img|nii)', 'f' )
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
art art - module for automatic and manual detection and removal of outliers.
calculateDurations CALCULATEDURATIONS Summary of this function goes here
processPresentation PROCESS Summary of this function goes here
log_to_condition reads in the logfile - each column will be a variable, first 5 lines are
findField
SOURCE CODE
function [ output ] = find(dirdata, pattern, type, depth)
%Find file using regular expression
%
%   Example of use: find('/dados1', '.*(img|nii)', 'f')
%
output = {};
maxdepth = '';
if(~exist('type', 'var')); type = 'd'; end;
if(exist('depth', 'var')); maxdepth = ['-maxdepth ' depth]; end;
findCmd = sprintf('find %s %s-regextype posix-extended -regex "%s" -type %s | sort', dirdata, maxdepth, pattern, type);
[~, finds] = system(findCmd);
if(~isempty(finds))
    finds = regexprep(finds,'\n*$', '');
    output = regexp(finds,'\n', 'split');
end
end