Description of remove_from_path
remove_from_path
PURPOSE
SYNOPSIS
function remove_from_path(exclude)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
spm12
spm8
spm12
spm8
SOURCE CODE
function remove_from_path(exclude)
p = path;
r = p;
while true
    [t r] = strtok( r, ':');
    if ~isempty( strfind( t, exclude ) )
        rmpath( t );
    end
    if isempty( r ), break, end
end